### ISSUE TITLE
Make unsecure links use HTTPS

### ISSUE THREAD

**Issue by Daniel-Dixon-UTC** [FlawCon/flawcon.github.io#4]
Links in the nav bar do not use HTTPS. "http://" needs replacing with "https://" on every link with every page.

**Comment by tomfairey** [comment]
It is best to just use relative links a.k.a "/" or "/info" instead.

**Comment by Daniel-Dixon-UTC** [comment]
Fixed as of commit https://github.com/flawcon/flawcon.github.io/commit/80c44fed36f3052446b1d2ba5cd43398473dcdbc
