### ISSUE TITLE
Remove Uses HTML Footer

### ISSUE THREAD

**Issue by Daniel-Dixon-UTC** [FlawCon/flawcon.github.io#5]
Causes compatibility issues with mobile versions

**Comment by LordBonzi** [comment]
Shouldn't do, seen as though is just a footer tag that has an image inside a center tag

**Comment by Daniel-Dixon-UTC** [comment]
Fixed as of https://github.com/FlawCon/flawcon.github.io/commit/33c52e4f8bf9fbde533107ce1737e110fd088926

**Comment by LordBonzi** [comment]
Removed the Uses HTML image and fixed other footer centering issues as of https://github.com/FlawCon/flawcon.github.io/commit/3e3ce366066f500cb957672e0aa49336ad053c78
